In [1]:
import numpy as np
import pandas as pd


In [2]:
from sklearn import preprocessing
import sklearn
from numpy.random import seed
# from keras import optimizers
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

seed = 7
np.random.seed(seed)

In [3]:
df = pd.read_csv("winemag-data-year_parsed.csv")
df.head()
df=df.drop( columns='Column1')
df=df.drop_duplicates()
df.count()

country                  118849
description              118908
designation               84716
points                   118908
price                    110579
province                 118849
region_1                  99555
region_2                  46203
taster_name               94194
taster_twitter_handle     89705
title                    118908
variety                  118907
winery                   118908
year                     114952
stars                    118908
description_len          118908
dtype: int64

In [4]:
df.head(3)

country                                        description   designation  \
0     Italy  Aromas include tropical fruit, broom, brimston...  Vulkà Bianco   
1  Portugal  This is ripe and fruity, a wine that is smooth...      Avidagos   
2        US  Tart and snappy, the flavors of lime flesh and...           NaN   

   points  price           province           region_1           region_2  \
0      87    NaN  Sicily & Sardinia               Etna                NaN   
1      87   15.0              Douro                NaN                NaN   
2      87   14.0             Oregon  Willamette Valley  Willamette Valley   

     taster_name taster_twitter_handle  \
0  Kerin O’Keefe          @kerinokeefe   
1     Roger Voss            @vossroger   
2   Paul Gregutt           @paulgwine    

                                           title         variety  \
0              Nicosia 2013 Vulkà Bianco  (Etna)     White Blend   
1  Quinta dos Avidagos 2011 Avidagos Red (Douro)  Portuguese Red   
2  Rainstorm 2013 Pinot Gris (Willamette Valley)      Pinot Gris   

                winery    year  stars  description_len  
0              Nicosia  2013.0      2              172  
1  Quinta dos Avidagos  2011.0      2              227  
2            Rainstorm  2013.0      2              186

DROPPED NULL VALUES AND FILETERED OUT WINE OLDER THAN 1944

In [5]:
selected_data=df[['country','description','points','price','province','region_1','title','variety','year','stars','description_len','winery']]
selected_dropna=selected_data.dropna()
selected_dropna=selected_dropna[selected_dropna['year'] >1944]

In [6]:
selected_dropna.head(4)

country                                        description  points  price  \
2      US  Tart and snappy, the flavors of lime flesh and...      87   14.0   
3      US  Pineapple rind, lemon pith and orange blossom ...      87   13.0   
4      US  Much like the regular bottling from 2012, this...      87   65.0   
5   Spain  Blackberry and raspberry aromas show a typical...      87   15.0   

         province             region_1  \
2          Oregon    Willamette Valley   
3        Michigan  Lake Michigan Shore   
4          Oregon    Willamette Valley   
5  Northern Spain              Navarra   

                                               title             variety  \
2      Rainstorm 2013 Pinot Gris (Willamette Valley)          Pinot Gris   
3  St. Julian 2013 Reserve Late Harvest Riesling ...            Riesling   
4  Sweet Cheeks 2012 Vintner's Reserve Wild Child...          Pinot Noir   
5  Tandem 2011 Ars In Vitro Tempranillo-Merlot (N...  Tempranillo-Merlot   

     year  stars  description_len        winery  
2  2013.0      2              186     Rainstorm  
3  2013.0      2              199    St. Julian  
4  2012.0      2              249  Sweet Cheeks  
5  2011.0      2              261        Tandem

In [7]:
selected_data=selected_dropna[['country','price','region_1','variety','year','stars','description_len','winery']]
points_selected=[]

selected_data.dtypes

country             object
price              float64
region_1            object
variety             object
year               float64
stars                int64
description_len      int64
winery              object
dtype: object

In [8]:
X = selected_data.select_dtypes(include=[object])
X.head(3)

country             region_1     variety        winery
2      US    Willamette Valley  Pinot Gris     Rainstorm
3      US  Lake Michigan Shore    Riesling    St. Julian
4      US    Willamette Valley  Pinot Noir  Sweet Cheeks

In [9]:
# # FUNCTION FOR FITTING AND TRANSFORMING NON-NUMERIC DATA INTO NUMERIC

# # TODO: create a LabelEncoder object and fit it to each feature in X

# # 1. INSTANTIATE
# # encode labels with value between 0 and n_classes-1.
# le = preprocessing.LabelEncoder()
# # 2/3. FIT AND TRANSFORM
# # use df.apply() to apply le.fit_transform to all columns
# #CREATE A FUNCTION
# def transformed(transform_this):
#     user_input1 = transform_this.apply(le.fit_transform)
#     return (user_input1)
import matplotlib.pyplot as plt
import numpy as np
import sklearn
import sklearn.datasets
from numpy.random import seed
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
seed(0)


# TODO: create a LabelEncoder object and fit it to each feature in X


# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
le = preprocessing.LabelEncoder()


# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
X_2 = X.apply(le.fit_transform)




In [10]:
#FIT AND TRANSFORM NON NUMERIC DATA USING 'transformed' FUNCTION
# X_2 = transformed(X)
X_2.head()


country  region_1  variety  winery
2        6      1179      311   10353
3        6       530      340   11437
4        6      1179      315   11609
5        5       726      423   11676
6        4      1166      128   11936

VERIFY DATA AND EXPORT TO CSV

In [11]:
# THIS IS FOR VARIFYING THE DATA ---NOTHING TO DO WITH CODE---
verify_data=pd.DataFrame({
    'country_code': X_2['country'],
    'price': selected_dropna['price'],
    'region_1_code': X_2['region_1'],
    'variety_code': X_2['variety'],
    'year': selected_dropna['year'],
    'description_len': selected_dropna['description_len'],
    'country':selected_dropna['country'],
    'region_1': selected_dropna['region_1'],
    'variety': selected_dropna['variety'],
    'stars': selected_dropna['stars'],
    'points': selected_dropna['points'],
    'winery': selected_dropna['winery']
}
).reset_index(drop=True)
verify_data=verify_data[['country_code','description_len','price','region_1_code','variety_code','year','country','region_1','variety','stars','points','winery']]

verify_data.to_csv('verify_data.csv')
verify_data.head()

country_code  description_len  price  region_1_code  variety_code    year  \
0             6              186   14.0           1179           311  2013.0   
1             6              199   13.0            530           340  2013.0   
2             6              249   65.0           1179           315  2012.0   
3             5              261   15.0            726           423  2011.0   
4             4              181   16.0           1166           128  2013.0   

  country             region_1             variety  stars  points  \
0      US    Willamette Valley          Pinot Gris      2      87   
1      US  Lake Michigan Shore            Riesling      2      87   
2      US    Willamette Valley          Pinot Noir      2      87   
3   Spain              Navarra  Tempranillo-Merlot      2      87   
4   Italy             Vittoria            Frappato      2      87   

            winery  
0        Rainstorm  
1       St. Julian  
2     Sweet Cheeks  
3           Tandem  
4  Terre di Giurfo

In [12]:
#SELECTING THE CLASSES OUTPUT VALUES FOR CREATING CLASSES. THE STAR VALUES ARE USED TO REDUCE THE PROCESSING TIME. 
#THE ACCURACY OF THE MODEL IS BETTER WITH USING STARS THAN WITH POINTS

import keras

y=selected_dropna['stars'].values
# y=[80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100]
t=np.asarray(y)
t.shape

n=keras.utils.to_categorical(t, num_classes=None)
n.shape

/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


(89473, 6)

In [13]:
#INSERT THE TRANSFORMED DATA INTO THE DATAFRAME
# def dataframe_withtransformed_data(DF1, DF2):
#     new_data=pd.DataFrame({
#         'country': DF1['country'],
#         'price': DF2['price'],
#         'region_1': DF1['region_1'],
#         'variety': DF1['variety'],
#         'year': DF2['year'],
#         'description_len': DF2['description_len']
#     }).reset_index(drop=True)
#     return(new_data)

In [14]:
new_data=pd.DataFrame({
    'country': X_2['country'],
    'price': selected_dropna['price'],
    'region_1': X_2['region_1'],
    'variety': X_2['variety'],
    'year': selected_dropna['year'],
    'description_len': selected_dropna['description_len'],
    'winery':X_2['winery']
})
# .reset_index(drop=True)

In [15]:
#INSERT THE TRANSFORMED DATA INTO THE DATAFRAME
# new_data=dataframe_withtransformed_data(X_2,selected_dropna)

In [16]:
new_data=new_data[[
    'country',
    'price',
    'region_1',
    'variety',
    'year',
    'description_len',
    'winery'
]]
new_data.head()

country  price  region_1  variety    year  description_len  winery
2        6   14.0      1179      311  2013.0              186   10353
3        6   13.0       530      340  2013.0              199   11437
4        6   65.0      1179      315  2012.0              249   11609
5        5   15.0       726      423  2011.0              261   11676
6        4   16.0      1166      128  2013.0              181   11936

In [17]:
X=new_data.values
X[0]

array([6.0000e+00, 1.4000e+01, 1.1790e+03, 3.1100e+02, 2.0130e+03,
       1.8600e+02, 1.0353e+04])

In [18]:
# TRAIN AND TEST DATA SPLIT
X_train, X_test, y_train, y_test = train_test_split(X, n, random_state=1)
print(X_train.shape, y_train.shape)
X_train

(67104, 7) (67104, 6)


array([[4.0000e+00, 2.2000e+01, 1.9900e+02, ..., 2.0130e+03, 2.3400e+02,
        4.6470e+03],
       [4.0000e+00, 3.9000e+01, 1.1130e+03, ..., 2.0060e+03, 1.9900e+02,
        8.2000e+03],
       [6.0000e+00, 2.0000e+01, 9.7600e+02, ..., 2.0120e+03, 2.4000e+02,
        7.0190e+03],
       ...,
       [0.0000e+00, 5.0000e+01, 1.0710e+03, ..., 2.0130e+03, 3.4200e+02,
        1.0836e+04],
       [4.0000e+00, 2.6000e+01, 2.6400e+02, ..., 2.0130e+03, 2.4200e+02,
        1.0774e+04],
       [3.0000e+00, 1.5000e+03, 9.0300e+02, ..., 2.0100e+03, 3.6800e+02,
        2.5290e+03]])

In [19]:
#SCALING X_train and y_train
X_scaler = StandardScaler().fit(X_train)
y_scaler = StandardScaler().fit(y_train)
X_scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [20]:
#SCALING X_train and y_train
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

y_train_scaled = y_scaler.transform(y_train)
y_test_scaled = y_scaler.transform(y_test)

In [21]:
X_train_scaled[0]

array([-0.46330429, -0.35037765, -1.10501992,  0.76539976,  0.67688679,
       -0.16422768, -0.59700007])

In [22]:
from keras.models import Sequential

model = Sequential()
from keras.layers import Dense
number_inputs = 7
number_hidden_nodes = 8
model.add(Dense(units=number_hidden_nodes,
                activation='relu', input_dim=number_inputs))
model.add(Dense(units=12, activation='relu'))
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=8, activation='relu'))
model.add(Dense(units=16, activation='relu'))

In [23]:
number_classes = 6
model.add(Dense(units=number_classes, activation='sigmoid'))


In [24]:
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 8)                 64        
_________________________________________________________________
dense_2 (Dense)              (None, 12)                108       
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 104       
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 16)                144       
_________________________________________________________________
dense_6 (Dense)              (None, 6)                 102       
Total params: 594
Trainable params: 594
Non-trainable params: 0
_________________________________________________________________


In [25]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [26]:
model.fit(
    X_train_scaled,
    y_train,
    epochs=50,
    shuffle=True,
    verbose=2
)

Epoch 1/50
 - 3s - loss: 0.3059 - acc: 0.8482
Epoch 2/50
 - 3s - loss: 0.2673 - acc: 0.8662
Epoch 3/50
 - 3s - loss: 0.2648 - acc: 0.8676
Epoch 4/50
 - 3s - loss: 0.2623 - acc: 0.8686
Epoch 5/50
 - 3s - loss: 0.2607 - acc: 0.8695
Epoch 6/50
 - 3s - loss: 0.2598 - acc: 0.8699
Epoch 7/50
 - 3s - loss: 0.2589 - acc: 0.8709
Epoch 8/50
 - 3s - loss: 0.2585 - acc: 0.8709
Epoch 9/50
 - 3s - loss: 0.2579 - acc: 0.8714
Epoch 10/50
 - 3s - loss: 0.2575 - acc: 0.8715
Epoch 11/50
 - 3s - loss: 0.2571 - acc: 0.8717
Epoch 12/50
 - 3s - loss: 0.2569 - acc: 0.8719
Epoch 13/50
 - 3s - loss: 0.2568 - acc: 0.8721
Epoch 14/50
 - 3s - loss: 0.2565 - acc: 0.8718
Epoch 15/50
 - 3s - loss: 0.2564 - acc: 0.8719
Epoch 16/50
 - 3s - loss: 0.2562 - acc: 0.8723
Epoch 17/50
 - 3s - loss: 0.2560 - acc: 0.8727
Epoch 18/50
 - 3s - loss: 0.2559 - acc: 0.8729
Epoch 19/50
 - 3s - loss: 0.2557 - acc: 0.8726
Epoch 20/50
 - 3s - loss: 0.2556 - acc: 0.8728
Epoch 21/50
 - 3s - loss: 0.2557 - acc: 0.8727
Epoch 22/50
 - 3s - lo

In [27]:
model_loss, model_accuracy = model.evaluate(
    X_test_scaled, y_test, verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Loss: 0.25567159434971415, Accuracy: 0.8726735062824927


In [52]:
user_dict={
    'country': 'US',
    'price': 25,
    'region_1': 'Yolo County',
    'variety': 'Albariño',
    'year': 2015,
    'description_len': 246,
    'winery':'Berryessa Gap'
}

In [53]:
user_input=pd.DataFrame(user_dict,index=[0])
user_input

country  description_len  price     region_1    variety         winery  year
0      US              246     25  Yolo County  Albariño  Berryessa Gap  2015

In [54]:
user_inputX = user_input.select_dtypes(include=[object])
user_inputX.head(3)

country     region_1    variety         winery
0      US  Yolo County  Albariño  Berryessa Gap

In [55]:
# TODO: create a LabelEncoder object and fit it to each feature in X


# 1. INSTANTIATE
# encode labels with value between 0 and n_classes-1.
le = preprocessing.LabelEncoder()


# 2/3. FIT AND TRANSFORM
# use df.apply() to apply le.fit_transform to all columns
X_2 = user_inputX.apply(le.fit_transform)
X_2.head()

country  region_1  variety  winery
0        0         0        0       0

In [56]:
new_user_data=pd.DataFrame({
    'country': X_2['country'],
    'price': user_input['price'],
    'region_1': X_2['region_1'],
    'variety': X_2['variety'],
    'year': user_input['year'],
    'description_len': user_input['description_len'],
    'winery':X_2['winery']
    
}).reset_index(drop=True)

new_user_data

country  description_len  price  region_1  variety  winery  year
0        0              246     25         0        0       0  2015

In [57]:
new_user_data=new_user_data[['country','price','region_1','variety','year','description_len','winery']]


# country	price	region_1	variety	year	description_len	winer

In [58]:
new_user_data_scalar=X_scaler.transform(new_user_data)
new_user_data_scalar

array([[-2.91574344, -0.28234198, -1.65078094, -1.70835134,  1.22864131,
         0.0110911 , -1.80053047]])

In [59]:
print(f"Predicted class: {model.predict_classes(new_user_data_scalar)}")

Predicted class: [3]
